### PR TITLE
make code block support add language hint like other Markdown Editor

### PR DESCRIPTION
**Pull request by timesking**
for example, just in github. 
```markdown
\```python
import os
\```
```
rendered as
```python
import os
```

### CODE REVIEW

**Comment by LegendRhine** [comment]
Hi, @timesking  Thanks for your PR. 

Just out of curiosity, does the language-auto-detect not satisfied?

**Comment by timesking** [comment]
It's a kind of compitable grammar. Some users like me,  I have a lot markdown files edited by Tyopra, MarkdownPad, Mweb, github, all of these support it.

If WDTP do not support it, all that files have to be edit again

**Comment by timesking** [comment]
add me if you use QQ: 15111625

**Comment by LegendRhine** [comment]
Yes, @timesking  This is the case  indeed. I consider of it as a 'traditional flaw' and try to avoid/change it as far as I can go. The simplest way to solve this: 

In WDTP, import the docs you want into a dir, right click on that dir in file tree panel and 'Replace Content...' Let all language-postfixs turn into an empty. Replace '\```python' to '\```' e.g..

**Comment by timesking** [comment]
To compiatable with this kind of code block is important for attracting users who has already some Markdown articles edited by Github Markdown, Tyopra, MarkdownPad2, Mweb.

And this kind of code block makes inserting sequence diagram possible.

I thought you should consider it.

**Comment by LegendRhine** [comment]
Fine.  I've added your code in the source. 
https://github.com/LegendRhine/WDTP/commit/3c4edbb323067cee7b708a51cffa560e58c466aa

Thanks!

**Pull request closed without merging**
